import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const booksDir = path.resolve(__dirname, '../src/data/books');
const outputFilePath = path.resolve(__dirname, '../src/data/booksMetadata.ts');

async function run() {
  console.log('Starting metadata generation...');
  const files = fs.readdirSync(booksDir)
    .filter(file => file.endsWith('.ts') && !file.endsWith('Metadata.ts'));

  const allMetadata: any[] = [];

  for (const file of files) {
    const filePath = path.join(booksDir, file);
    try {
      const module = await import(filePath);
      const exportKey = Object.keys(module).find(key => key.startsWith('books'));
      if (exportKey) {
        const books = module[exportKey];
        if (Array.isArray(books)) {
          for (const book of books) {
            allMetadata.push({
              id: book.id,
              date: book.date,
              title: book.title,
              author: book.author,
              category: book.category,
              coverGradient: book.coverGradient,
              description: book.description,
              coreTakeaway: book.coreTakeaway,
              tags: book.tags || [],
              targetAudience: book.targetAudience || []
            });
          }
        }
      }
    } catch (err) {
      console.error(`Error importing ${file}:`, err);
    }
  }

  // Sort descending by date
  allMetadata.sort((a, b) => b.date.localeCompare(a.date));

  const fileContent = `// This file is auto-generated by scripts/generate-metadata.ts. Do not edit manually.
import { BookMetadata } from '../booksData';

export const booksMetadata: BookMetadata[] = ${JSON.stringify(allMetadata, null, 2)};
`;

  fs.writeFileSync(outputFilePath, fileContent, 'utf-8');
  console.log(`Successfully generated metadata for ${allMetadata.length} books at: ${outputFilePath}`);
}

run().catch(err => {
  console.error('Metadata generation failed:', err);
  process.exit(1);
});
